### ISSUE TITLE
Incompatible with Anki 23.10 - Windows - Qt6

### ISSUE THREAD

**Issue by liuxiao6110** [iamjustkoi/StudyTimeStats#37] opened 2023-09-25 09:13 UTC
Could you please try to make the plugin compatible with the Anki 23.10 beta1 - Windows - Qt6 version? This version updated the FSRS, which is important to me.

**Comment by iamjustkoi** [comment] 2023-09-25 16:34
Yeah, will try and see if I can update it this week! 

Hopefully it'll work with the pull request by [pangdaxing23](https://github.com/pangdaxing23) that I just accepted and merged with the main branch, recently!

Thanks for the report/request! ^^

**Comment by Static123h** [comment] 2023-11-03 22:35
Hey, i having the same issue, and anki redirected me here to look check for an update. was wondering if you could let us know when you go about updating this for 23.10 - windows - qt6. thanks for the amazing add on!

**Comment by Andrew15-5** [comment] 2023-11-06 01:44
The problem is with Anki 23.10 Qt6 version in general and is not platform dependent. Right now there is only [23.10](https://github.com/ankitects/anki/releases/tag/23.10) and [23.10.1rc1](https://github.com/ankitects/anki/releases/tag/23.10.1rc1). So the title should be updated to "Incompatible with Anki 23.10 Qt6".

https://github.com/ankitects/anki/releases/tag/23.10:

> Notable changes
> 
> - Quite a few add-ons will need updates to support the Qt 6 version of this release. Some [porting notes](https://forums.ankiweb.net/t/porting-tips-for-anki-23-10/35916) are available.

**Comment by iamjustkoi** [comment] 2023-11-11 17:35
Sorry this is still happening, for now moving this over to #39!

Thanks for the updates, though, and will try to see what I can do as soon as I can!

**Closed by iamjustkoi** 2023-11-11 17:35 UTC
Labels: bug, duplicate
