### ISSUE TITLE
No longer supported on Version 23.12.1?

### ISSUE THREAD

**Issue by snaxinhd** [iamjustkoi/StudyTimeStats#44] opened 2024-01-08 22:00 UTC
**Bug/Issue Description**
Add on startup failed on latest version of anki
**To Reproduce**
Steps to reproduce:
1. Open anki on the latest version
2. See error

I'm sorry if this report is not formatted correctly, I just joined GitHub. And, thank you so much for the add on, I have found it so motivating!

**Comment by AustinHasten** [comment] 2024-01-10 15:48
Check existing issues before creating one.
https://github.com/iamjustkoi/StudyTimeStats/issues/40

**Comment by snaxinhd** [comment] 2024-01-10 20:38
Hi - I had checked. The add-on worked perfectly for me when that issue was reported. I've opened a new one because I thought that this was to do with the add-on not being supported with the latest version. But, I'll check again to see if the fix for that issue will work for mine.

**Comment by snaxinhd** [comment] 2024-01-10 20:39
> Check existing issues before creating one. #40

Hi - I had checked. The add-on worked perfectly for me when that issue was reported. I've opened a new one because I thought that this was to do with the add-on not being supported with the latest version. But, I'll check again to see if the fix for that issue will work for mine.

**Comment by AustinHasten** [comment] 2024-01-10 20:40
Sounds like you hadn't upgrade to 23.10 at the time of the existing issue in that case. This addon will not work for anyone who upgrades to 23.10+.

**Comment by iamjustkoi** [comment] 2024-01-14 00:46
> Sounds like you hadn't upgrade to 23.10 at the time of the existing issue in that case. This addon will not work for anyone who upgrades to 23.10+.

Yeah this seems like it could be the case. 

Either way, appreciate the report and will merge as a duplicate of #40, for the time being!
Thanks again, will be trying to merge PR #43 and push an update/fix for this as soon as I can! ^^

**Closed by iamjustkoi** 2024-01-14 00:46 UTC
Labels: issue
